### ISSUE TITLE
Hello Open Source // 3 Coffees

### ISSUE THREAD

**Issue by bellanov** [bellanov/serenade-flow#12]
Congratulations on your first **Open Source** baby. The direction this will take is a lot more clear to me now.

**Tasks:**

- Review the current state of the project
- Brush up on _GraphQL_
- Brush up on _TypeScript_
   - Will be using _Svelte_ for web frontends and _React Native_ for mobile
- Read a bit about wasmCloud => https://wasmcloud.com/

**Comment by bellanov** [comment]
We'll resume working together on defining the CONTRIBUTING guide, as more people will be joining our Open Source journey.

**Comment by bellanov** [comment]
I've also added you to this project such that you can traverse your tickets across lanes.

**Comment by aybanda** [comment]
@bellanov 
done brushing up with graphql, typescript and svelte for web
working on react native 
PR is on its way 
make time for reviewing it

**Comment by aybanda** [comment]
also would you want me to work on integrating wasm ? or you will take care of that

**Comment by bellanov** [comment]
Sounds good. I'm getting into React Native now so I'll be following your lead there.

I liked your first stab at the ETL.

Need more formal process than code at the moment, so you can hold off on React Native for now. I'll create another issue with details.

Things need to be real products now that we're kinda live. Other people are looking at this already so it's smarter to operate here for now. No more boilerplate/hello worlds when there is a clear direction!

Your name also isn't in your GitHub profile, just your README. Just put Ajay.

**Comment by aybanda** [comment]
<img width="1440" alt="Screenshot 2024-09-21 at 8 18 14 PM" src="https://github.com/user-attachments/assets/5814c4fc-f91c-49e8-83e7-3485e643f572">

**Comment by aybanda** [comment]
<img width="1440" alt="Screenshot 2024-09-21 at 8 18 27 PM" src="https://github.com/user-attachments/assets/64aaa23a-f44b-4dc9-81e5-d12470fc6816">

**Comment by aybanda** [comment]
<img width="1077" alt="Screenshot 2024-09-21 at 9 47 45 PM" src="https://github.com/user-attachments/assets/5acb8414-930c-4126-a0c7-78708302f35c">

**Comment by bellanov** [comment]
Did a bit more research and found that this is a bit more promising as a **GraphQL** client. Looks like a good up-and-comer. GraphQL seems more suited for personal projects, not production ones. 

This one has my attention kinda.
https://altairgraphql.dev/docs/

**Comment by bellanov** [comment]
> also would you want me to work on integrating wasm ? or you will take care of that

No, stop doing things not assigned to you. That's literally the point of this ticketing system lol.

Just like with this issue, I'll create one for each task and assign it to you. 

Good job, now just simply sit still. I need to work on the contributing guide so these steps are clear.

**Comment by bellanov** [comment]
This one also looks pretty good. Gonna have to compare the two.

https://testfully.io/blog/graphql-clients/#hoppscotch

**Comment by aybanda** [comment]
> > also would you want me to work on integrating wasm ? or you will take care of that
> 
> No, stop doing things not assigned to you. That's literally the point of this ticketing system lol.
> 
> Just like with this issue, I'll create one for each task and assign it to you.
> 
> Good job, now just simply sit still. I need to work on the contributing guide so these steps are clear.

cool
checking just in case

**Comment by aybanda** [comment]
> This one also looks pretty good. Gonna have to compare the two.
> 
> https://testfully.io/blog/graphql-clients/#hoppscotch

Altair GraphQL is more versatile in my opinion.

**Comment by bellanov** [comment]
Gotcha, I shall take your word for it!!!!

On that note, another set of tasks afoot.
