### ISSUE TITLE
Learn How to Use GitHub Projects // 2 Coffees

### ISSUE THREAD

**Issue by bellanov** [bellanov/serenade-flow#17]
Learn how to use a ticketing system.

https://github.com/users/bellanov/projects/18

**Tasks:**

- Create an issue called "Update CONTRIBUTING Guide" tied to the **serenade-flow** repository
- Create a branch from the created issue
- Move the issue into the "In Progress" lane

We'll work on one task together so you can get the development workflows (API Keys, etc.)

**Comment by bellanov** [comment]
It's simply drag-and-drop across the lanes. You should have an invite to view this project.

![Image](https://github.com/user-attachments/assets/3e86555b-33ac-43eb-9020-39fa5e514b94)

**Comment by bellanov** [comment]
Just one more thing and we're done here. Assign it to yourself so it'll immediately pop up on the board.

![Image](https://github.com/user-attachments/assets/cfe94903-a9f3-4f4f-ab0f-8bb180acc04e)

**Comment by aybanda** [comment]
Hey I do not know you gave me the write access 
its done now

**Comment by bellanov** [comment]
Awesome

**Comment by bellanov** [comment]
Getting to your coffees in a bit.

I'm curious Ajay, where are you from?

**Comment by aybanda** [comment]
India , why do you ask ?

**Comment by bellanov** [comment]
Ah, I was just curious, as Open Source is a wonderful thing.

**Comment by bellanov** [comment]
Closing this. In the future, the PRs attached to the issue will close it.

**Comment by aybanda** [comment]
Indeed 

> Ah, I was just curious, as Open Source is a wonderful thing.

Indeed powerful as well
