### ISSUE TITLE
PyPi API Key for Ajay

### ISSUE THREAD

**Issue by bellanov** [bellanov/serenade-flow#22]
Create a key to enable Ajay to push and test from **testpypi** directly. Avoiding any local uniqueness whenever possible.

**Comment by bellanov** [comment]
@aybanda We'll work out the _API Key_ handoff and _Development Workflow_ updates here.

**Comment by bellanov** [comment]
@aybanda Should be squared up on coffees. Upping this one to **3,** as I feel I underestimated.

**Comment by aybanda** [comment]
Alright, you mentioned earlier you have my email to get me the copy (just reminding you).

**Comment by bellanov** [comment]
Caught up getting the other guy to speed a bit. Done updating my Terraform projects so he has some work to do. 

I'll add you to those as well so you can see the issues, and eventually deploy your own changes.

**Comment by bellanov** [comment]
Going to be testing the key locally shortly. Will let you know when I send the email. It'll be an email with sensitive content so you'll have to MFA via a provided code, etc.

**Comment by bellanov** [comment]
Sorry for the delay. Amidst onboarding the other guy on the Terraform IaC side of things. 

Can't wait to see how fast we all move once we get going. Got lots of ETL things to try to accomplish.

**Comment by bellanov** [comment]
Going to try again using my password manager. It should be able to create a secure, one-use link that I can easily share with you!

**Comment by aybanda** [comment]
Hey @bellanov 
I've tested with provide key, everything is going smoothly
<img width="917" alt="Screenshot 2024-10-06 at 10 21 10 AM" src="https://github.com/user-attachments/assets/9d610818-92fc-4dbb-8ae8-b5997a25bc87">
