### ISSUE TITLE
Discuss FantasyAce

### ISSUE THREAD

**Issue by bellanov** [bellanov/serenade-flow#27]
Discuss **FantasyAce** and ideate with regards to how **SerenadeFlow** can facilitate its various data pipelines.

**FantasyAce Pipelines**

- Data Scraping
  - Scrape sports betting information from various Bookies for _analysis_.
- Data Analysis
   - Analyze scraped data and generate more complex metrics / analytics that will _inform decisions_.
- Inform Decisions
   - Once analytics are generated that can inform decisions, this information needs to be relayed to end users (email, text, app notification, etc.)

**Comment by aybanda** [comment]
Hey @bellanov . I believe SerenadeFlow can be effectively adapted to handle these pipelines. Here's a proposed approach:

For scraping data:
- We can create a bunch of small, focused modules for each bookie's website or API.
- This way, we can easily add new sources or update existing ones without messing with the whole system.
- Plus, we can grab data from multiple places at once, which should speed things up.

For crunching the numbers:
- Let's break down the analysis into bite-sized pieces that we can mix and match.
- We'll cover the basics like cleaning up the data and comparing odds across different bookies.
- But here's where it gets fun – we can also add in some cool stuff like spotting value bets or finding arbitrage opportunities.

For sharing the insights:
- We'll make it super easy to get the good stuff out to the people who need it.
- Think API endpoints for other systems, email alerts for hot tips, and slick dashboards for the visual folks.

Here's how I see us tackling this:
1. We'll start small – maybe pick one bookie and one type of analysis to get the ball rolling.
2. Then we'll show it off, get some feedback, and keep improving from there.
3. As we go, we'll add more sources and fancier analyses.

we can adapt as we learn what works best for FantasyAce. What do you think?

**Comment by bellanov** [comment]
I honestly wasn't expecting this in-depth level of analysis,  let alone so quickly.

I'm very glad that you have some of the working knowledge I seek, after you mentioned arbitrage.

Looking forward to getting these pipelines going and seeing what's what.

**Comment by aybanda** [comment]
> I honestly wasn't expecting this in-depth level of analysis, let alone so quickly.
> 
> I'm very glad that you have some of the working knowledge I seek, after you mentioned arbitrage.
> 
> Looking forward to getting these pipelines going and seeing what's what.

Thanks for the feedback! after serenade-flows implementation got quite excited with ideas and explored different ways to provide suitable implementations, researched few things but it made even more workable when you detailed it out in this issue, also your work ethic really helping me a lot to bring results fast.

**Comment by aybanda** [comment]
> I honestly wasn't expecting this in-depth level of analysis, let alone so quickly.
> 
> I'm very glad that you have some of the working knowledge I seek, after you mentioned arbitrage.
> 
> Looking forward to getting these pipelines going and seeing what's what.

Thanks for the feedback! after serenade-flows implementation got quite excited with ideas and explored different ways to provide suitable implementations, researched few things but it made even more workable when you detailed it out in this issue, also your work ethic really helping me a lot to bring results fast.
