### ISSUE TITLE
Proposal for FantasyAce Data Pipeline

### ISSUE THREAD

**Issue by aybanda** [bellanov/serenade-flow#29]
Hey @bellanov 

I’m excited to propose a plan for developing a data pipeline for FantasyAce. Our goal is to scrape, analyze, and deliver valuable betting insights to help our users make informed decisions. Here’s what I have in mind

Objectives:

Create a solid data scraping module for popular bookies.
Analyze the data to uncover valuable betting insights.
Share actionable analytics with our users through various channels.

Proposed Pipeline Steps:

Bookie Selection:

Let’s confirm our focus on these popular bookies:
Underdog
PrizePicks
DraftKings
FanDuel

Data Scraping Module:

We’ll start by building a scraping module for our chosen bookies, focusing on:
"Anytime TD Scorer" bets and other key data points.
Using the Player Card pattern for efficient data extraction.
Tackling authentication challenges, especially for Underdog.

3. Data Analysis:

Next, we’ll develop scripts to analyze the scraped data, including:
Spotting trends and patterns in betting data.
Calculating metrics that highlight potential betting edges.

4. Delivery Mechanism:

We’ll create a system to deliver insights to our users, such as:
Email alerts for important findings.
API endpoints for easy integration with other apps.
Dashboards for a visual representation of the data.

Documentation and Testing:

Let’s document the entire process for future reference and ensure everything is tested for reliability and accuracy.

I’d love to hear your thoughts on this proposed pipeline!

Your feedback and ideas are super welcome!

Also, would it be possible to discuss whatever reward for the effort put into developing the FantasyAce data pipeline?

I’m really looking forward to implement this and making a positive impact in the sports betting space. Let’s make this happen! 🚀

**Comment by bellanov** [comment]
No rewards until we get subs and still very far from that. Til then all I have are coffees ☕️ for Open Source contributions.

Don't feel like you need to overdo things or have to stick around.

Once I get there, I get to query all of these coffees / estimates and see if anyone is worth rewarding.

That is the core idea of this Andy project you see around the repository.

Creating an army of open source contributors and the top 10 get a cut of the projects profits.

Also very far away from that idea as well.

**Comment by aybanda** [comment]
No worries, I appreciate the transparency about the project’s progress. I’m happy to contribute where I can and will stick around to see how things develop.

**Comment by bellanov** [comment]
Yea, I have a couple of ideas that are just so stupid that they may work. If one sticks and you develop for it, it means ye get a cut.

**Comment by bellanov** [comment]
I love the ideas here. They are in line with what I'm thinking.

**Comment by aybanda** [comment]
@bellanov 
Thank you for the feedback! I’m glad the ideas resonate with you. I agree that using Rust for data scraping could be beneficial. Let’s keep moving forward!

**Comment by bellanov** [comment]
But in general, the goal is to create something that executes as fast as the bookies can change their lines, which is why things like RUST, Go, and WASM come into play.

Looking forward with playing with new technologies and patterns!
